# Generated by Django 3.0.7 on 2020-08-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partyapp', '0002_auto_20200808_2248'),
        ('partyapp', '0003_auto_20200808_1658'),
    ]

    operations = [
    ]
